### PR TITLE
Add php8 compatibility.

### PR DESCRIPTION
**Pull request by rodrigoaguilera**
I wanted to do some robo 3.x development with php 8 and the first thing I found is that this plugin is not compatible with php 8.
Then I found that semver 1.x is not compatible with php 8 and the only way to get semver 3.x is depending on composer 2.
That forces the plugin to be compatible with the new API.

The most difficult part was to figure out that in order to write a lockfile composer 2 needs to have the `executeOperations` set to true, therefore no `->setExecuteOperations(false)`. I just left the default for composer 2.

I ran all the tests successfully except for the codesniffer that needs to be updated to v3 to be compatible with php 8. Do you think that should be included as part of this change or you prefer a separate PR?

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
Thanks for starting this off.

The current test failures are a gordian knot of chicken-and-egg dependencies, since the tests expect compatibility with dev-main of this project.

If I just blindly merge here, could you make a follow-up PR to get tests to green, e.g. change vestigial dev-master references to dev-main, etc.?

**Comment by rodrigoaguilera** [comment]
All green now, even the codesniffer (no biggie since it doesn't need any configuration). 
There was an old reference to master with the placeholdering of __BRANCH__.
For the php5 test I just raised the minimum version of composer to one that includes the constant that I use for checking the composer version.

I suggest to drop support for PHP5 but I'll leave the .travis.yml up to you.
From my side this is good to merge.

**Comment by greg-1-anderson** [comment]
Oh, great -- from the failures I was concerned that it wouldn't be possible to get the tests to pass until the main branch was updated. Glad you were able to fix it up without doing that.

I don't want to drop old PHP version support unless it also comes with a major version bump. As long as that's not necessary, I'll just keep the old version support in for now.

Thanks for doing this.

**Comment by greg-1-anderson** [comment]
Released version 3.2.0.

**Pull request merged**
